import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <nav className="w-full flex items-center justify-between px-6 py-4 bg-white border-b border-[var(--border)] mb-8 sticky top-0 z-50">
          <div className="text-2xl font-bold text-[var(--foreground)] tracking-tight">Campus Marketplace</div>
          <ul className="flex gap-6 text-base font-medium">
            <li><Link href="/" className="hover:text-black transition-colors">Home</Link></li>
            <li><Link href="/listings" className="hover:text-black transition-colors">Find Subleases</Link></li>
            <li><Link href="/post" className="hover:text-black transition-colors">Post a Sublease</Link></li>
            <li><Link href="/blog" className="hover:text-black transition-colors">Blog</Link></li>
            <li><Link href="/account" className="hover:text-black transition-colors">My Account</Link></li>
          </ul>
        </nav>
        <main className="max-w-5xl mx-auto px-4">{children}</main>
      </body>
    </html>
  );
}
